### PR TITLE
Less spaghett more sause...

### PR DESCRIPTION
**Pull request by 5m1Ly**
Made some changes around the thing let it work al little faster not that it realy matters and its less spaghetti any more 🙂

### CODE REVIEW

**Comment by 5m1Ly** [comment]
Yea sorry i didn't test it. at all because you should work accactly the same its just a diffrent way of writing what was allready there

**Comment by 5m1Ly** [comment]
Just tested the sliders on a qbcore server and they still work

**Comment by 5m1Ly** [comment]
on line 51 or 52 i missed a ; there and what exectly did you mean with implementing #21 (i'm guessing the entire pull request but not i'm sure)

**Comment by BombayV** [comment]
@5m1Ly What I meant was to implement the export so that people can trigger the hud once they finish with their multichar selection or whatever they want to do.

**Comment by 5m1Ly** [comment]
May i ask why?? I personaly get this approuch, it works faster and makes the use easier. But from experiance with personal released open source projects i stated that people are to ignorend and lazy to read documentation. So this doesnt make it user friendly. so to my opinion it would be better you dynamiccally use the required code based on the framework or make it a standalone.

**Pull request merged**
